#!/usr/bin/env python3
"""Slice the fonts listed in FONTS out of u8g2's 40 MB u8g2_fonts.c into
main/gui/gfx/gfx_fonts.c.

Compiling the upstream file whole costs minutes and gigabytes; we only ever want a
handful of fonts. Edit FONTS below and re-run:

    python3 tools/extract_fonts.py

The upstream file is cached in build/ on first run.
"""

import os
import re
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/olikraus/u8g2/master/csrc/u8g2_fonts.c"
GUI = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(os.path.dirname(GUI))
CACHE = os.path.join(ROOT, "build", "u8g2_fonts_upstream.c")
OUT_C = os.path.join(GUI, "gfx", "gfx_fonts.c")

# The order here is the order in gfx_font_table, which is the order the
# simulator renders its specimens in.
FONTS = [
    # text
    "u8g2_font_micro_tr",
    "u8g2_font_3x5im_tr",
    "u8g2_font_04b_03_tr",
    "u8g2_font_4x6_tr",
    "u8g2_font_micropixel_tr",
    "u8g2_font_resoledbold_tr",
    "u8g2_font_6x10_mr",
    # icons
    "u8g2_font_open_iconic_all_1x_t",
    "u8g2_font_unifont_t_weather",
    "u8g2_font_unifont_t_animals",
    "u8g2_font_unifont_t_77",
]


def upstream():
    if not os.path.exists(CACHE):
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        sys.stderr.write("fetching %s ...\n" % URL)
        urllib.request.urlretrieve(URL, CACHE)
    with open(CACHE, encoding="latin-1") as f:
        return f.read()


def slice_font(src, name):
    """Return (comment, definition) copied verbatim, so the byte data stays exact."""
    m = re.search(r"const uint8_t " + re.escape(name) + r"\[\d+\] U8G2_FONT_SECTION\(", src)
    if not m:
        raise SystemExit("font not found upstream: " + name)

    # The data is one long C string literal; a bare ';' also occurs *inside* it,
    # so track quoting instead of searching for the next semicolon.
    i, in_str = m.end(), False
    while i < len(src):
        c = src[i]
        if in_str:
            in_str = not (c == '"')
            i += 2 if c == "\\" else 1
            continue
        if c == '"':
            in_str = True
        elif c == ";":
            break
        i += 1

    head = src.rfind("/*", 0, m.start())
    return src[head:i + 1]


def main():
    fonts = FONTS
    src = upstream()
    parts = [slice_font(src, n) for n in fonts]

    with open(OUT_C, "w", encoding="latin-1") as f:
        f.write("/* Generated by tools/extract_fonts.py -- do not edit.\n"
                " * Fonts sliced from u8g2 (new-bsd, see components/u8g2/LICENSE).\n */\n\n")
        f.write('#include "gfx_fonts.h"\n\n')
        f.write("\n\n".join(parts))
        f.write("\n\nconst gfx_font_entry_t gfx_font_table[] = {\n")
        for n in fonts:
            f.write('    { "%s", %s },\n' % (n[len("u8g2_font_"):], n))
        f.write("};\n\nconst int gfx_font_count = %d;\n" % len(fonts))

    sys.stderr.write("wrote %s (%d fonts, %d KB)\n"
                     % (OUT_C, len(fonts), os.path.getsize(OUT_C) // 1024))


if __name__ == "__main__":
    main()
